title: 岛
url: https://yandaoyu.github.io
baseurl: '/Stories'
cdnurl: 'https://blog-biezhi-me-1251171175.cos.ap-shanghai.myqcloud.com'
description: >
  希望每个渴望都有寄托

permalink: /:year/:month/:title.html

image: /public/images/mountains.jpg
color: '#dc322f'
google_analytics: 
baidu_analytics: 2209f3e596f3e0c61a293f49a2f65ba3
# disqus: blog-biezhi-me

markdown: kramdown
highlighter: rouge
paginate: 12
paginate_path: "/page/:num"

# 作者信息
author:
  name: Island YAN
  email: yqy.yan@qq.com
  photo: /Stories/public/images/icebear.jpg

# 社交信息
# socials:
#   - title: Weico
#     icon: weico
#     url: https://github.com/biezhi

# 友链
links:
  - title: MyTechBlog
    url: https://yandaoyu.github.io

# html 压缩
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
  endings: all
  startings: [html, head, body]

# sass 解析
sass:
  sass_dir: public/css
  style: compressed

# 插件
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
